apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minha-aplicacao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:eugeniokleber/argocd-helm-infra.git
    targetRevision: main  # Branch alvo
    path: .               # Pasta onde está o chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true       # Remove recursos que foram deletados do repositório
      selfHeal: true    # Corrige recursos que foram alterados fora do Git
    syncOptions:
      - CreateNamespace=true
      - SyncTimeout=5m
      - ReSyncPeriod=10m
      - Force=true