apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: {{ .Values.hpa.metrics.type }}
    resource:
      name: {{ .Values.hpa.metrics.resource.name }}
      target:
        type: {{ .Values.hpa.metrics.resource.target.type }}
        averageUtilization: {{ .Values.hpa.metrics.resource.target.averageUtilization }}  # A média de utilização de CPU para escalonar